# telling Spring where to get the data from
spring:
    datasource:
        driverClassName: org.postgresql.Driver      # Driver needed to connect to postgres database
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: faster565

    output:
        ansi:
            enabled: ALWAYS
server:
    port: 8282                              # specifying port number


logging:
    level:
        com:
            skillstorm: debug               # making sure we print out our debug statements